fix CI2

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,14 +15,14 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      # 2. Set up Java (pakai 25 error di CI nya)
+      # 2. Set up JDK
       - name: Set up JDK
         uses: actions/setup-java@v4
         with:
           distribution: temurin
           java-version: 21
 
-      # 3. Cache Maven (biar build lebih cepat)
+      # 3. Cache Maven packages
       - name: Cache Maven packages
         uses: actions/cache@v4
         with:
@@ -33,20 +33,22 @@ jobs:
       - name: Build and test with Maven
         run: mvn clean verify
 
-      # 5. Upload JaCoCo report (optional tapi bagus)
+      # 5. Upload JaCoCo report
       - name: Upload JaCoCo report
         uses: actions/upload-artifact@v4
         with:
           name: jacoco-report
           path: target/site/jacoco/
-          
-       - name: Upload test report
+
+      # 6. Upload test report (only if failure)
+      - name: Upload test report
         if: failure()
         uses: actions/upload-artifact@v4
         with:
           name: surefire-reports
-          path: target/surefire-reports     
-          
-       - name: Print surefire logs
+          path: target/surefire-reports
+
+      # 7. Print surefire logs
+      - name: Print surefire logs
         if: failure()
-        run: cat target/surefire-reports/*.txt || true   
+        run: cat target/surefire-reports/*.txt || true
